### ISSUE TITLE
Curl-WASM source missing / inconsistency with ICT-Curl

### ISSUE THREAD

**Issue by mykronoer** [web-ict/ict#6]
**Bug description**
The source-code of curl-bg.wasm is missing; Additionally, it produces different results to the "final curl729_27" from sergejs ICT. Decompiled wasm looks like the java version, though. So, not really knowing what's going on there.

**Steps to reproduce**
1) create hash with curl from ICT; create hash with curl from WASM; Results differ.

**Expected behavior**
Same result.

**Comment by chrisdukakis** [comment]
Hi @mykronoer , curl source is here: https://github.com/web-ict/ict/blob/signing/curl/src/lib.rs
Will be later merged on master branch.

>Do you have a test-vector?

No test vector.
>is the new version wrong?

Probably it's correct. Will check again later.
> has the new version been changed?

Yes, curl intializes second part of null state with the length in trits of the message.

**Comment by mykronoer** [comment]
Thank you very much!

I'll close the ticket :+1:
